//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class cargos
    {
        public int ID { get; set; }
        public string nome_cargo { get; set; }
        public decimal salario { get; set; }
        public string nv_escolaridade { get; set; }
        public string nv_exp { get; set; }
        public string departamento { get; set; }
        public string status { get; set; }
        public Nullable<int> carga_horaria { get; set; }
    }
}
