//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class faltas
    {
        public int ID { get; set; }
        public Nullable<int> funcionarios_ID { get; set; }
        public System.DateTime data_falta { get; set; }
        public string motivo_falta { get; set; }
        public string justificativa { get; set; }
        public string observacoes { get; set; }
        public Nullable<int> duracao_falta { get; set; }
        public string tipo_falta { get; set; }
        public Nullable<int> historico_faltas { get; set; }
    }
}
