//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class holerite
    {
        public int data_emissao { get; set; }
        public string periodo_pagamento { get; set; }
        public Nullable<decimal> total_salario { get; set; }
        public Nullable<decimal> total_desconto { get; set; }
        public Nullable<decimal> total_liquido { get; set; }
        public Nullable<int> id_funcionario { get; set; }
        public Nullable<decimal> beneficios { get; set; }
        public Nullable<decimal> descontos { get; set; }
        public string status_pagamento { get; set; }
        public Nullable<decimal> decimo_terceiro { get; set; }
        public Nullable<decimal> salario_bruto { get; set; }
        public Nullable<int> mes_ref { get; set; }
        public Nullable<int> ano_ref { get; set; }
        public Nullable<decimal> inss { get; set; }
    }
}
